mixin () {
  /// Static Markdown documentation of the public backend API.
  public query func getApiDoc() : async Text {
    let lines : [Text] = [
      "# API del backend — Monitoreo de faroles",
      "",
      "Backend Motoko para el monitoreo de faroles (luminarias) y sus sensores. Los datos son **compartidos entre todos los usuarios autenticados**: no hay datos privados por usuario. La autenticación se realiza con Internet Identity.",
      "",
      "## Autenticación e identidad",
      "",
      "- Todas las lecturas (`listFaroles`, `getFarol`, `listPositions`, `listSensors`, `getSensor`, `listAlerts`, `getAlert`, `listDevices`) y todas las escrituras (`registerFarol`, `addSensor`, `updateSensorRange`, `recordReading`, `markAlertRead`, `linkDevice`, `unlinkDevice`) requieren un llamador **firmado** (no anónimo). Un llamador anónimo es rechazado.",
      "- El frontend fija un *derivation origin* de Internet Identity, publicado en `/.well-known/ii-derivation-origin` cuando está disponible. Un agente que ya tiene la autorización de Internet Identity del usuario deriva el principal correcto por aplicación contra ese origen (por ejemplo `icp identity link web <name> --app <host>`). Esa delegación actúa con toda la autoridad del usuario en esta app hasta que expira.",
      "- El registro de acceso ocurre solo cuando el llamador inicia sesión a través del frontend de la app. Un principal que nunca lo hizo está **no registrado** aunque pertenezca al propietario de la app, y un llamador firmado derivado contra otro origen es un principal distinto del registrado por el frontend. Un llamador no registrado recibe un rechazo en los endpoints protegidos.",
      "- Los datos son globales: cualquier usuario autenticado ve y modifica el mismo conjunto de faroles, sensores, alertas y dispositivos.",
      "",
      "## Unidades y codificación",
      "",
      "- `Timestamp`: entero de **nanosegundos** desde la época Unix (`Time.now()`).",
      "- `latitude` / `longitude`: grados decimales (`Float`).",
      "- `value`, `minValue`, `maxValue`, `lastValue`: `Float` en la unidad declarada por el campo `unit` del sensor (por ejemplo `°C`, `%`, `V`).",
      "- `SensorType`: variante `#movement | #humidity | #temperature | #battery`.",
      "- `SensorStatus`: variante `#normal | #outOfRange`.",
      "- `AlertReason`: variante `#belowMin | #aboveMax | #movementDetected`.",
      "- `farolId` en un sensor es opcional (`?FarolId`); `lastValue` y `lastReadingAt` son opcionales hasta que llega la primera lectura.",
      "- Los identificadores (`FarolId`, `SensorId`, `AlertId`, `DeviceId`, `PositionId`) son `Nat` asignados por el backend.",
      "",
      "## Endpoints",
      "",
      "### Faroles e historial de posiciones",
      "",
      "- `registerFarol(qrCode, name, latitude, longitude) -> FarolView` (update): registra un farol a partir del escaneo de su QR y captura la posición GPS del dispositivo. **Comportamiento upsert por `qrCode`**: si ya existe un farol con ese `qrCode`, no se crea otro; se añade una entrada al historial de posiciones y se devuelve el farol existente.",
      "- `listFaroles() -> [FarolView]` (query): todos los faroles registrados.",
      "- `getFarol(id) -> ?FarolView` (query): un farol por id, o `null`.",
      "- `listPositions(farolId) -> [PositionEntryView]` (query): historial de posiciones del farol, **ordenado de más reciente a más antiguo**.",
      "",
      "### Sensores",
      "",
      "- `addSensor(name, qrCode, sensorType, farolId, unit, minValue, maxValue) -> SensorView` (update): añade un sensor manualmente o desde su propio QR. El estado inicial es `#normal` y aún no tiene lectura.",
      "- `listSensors(sensorType, status, search) -> [SensorView]` (query): lista con filtros opcionales por tipo, estado y término de búsqueda.",
      "- `getSensor(id) -> ?SensorView` (query): un sensor por id, o `null`.",
      "- `updateSensorRange(id, minValue, maxValue) -> ?SensorView` (update): actualiza el rango mín/máx configurado del sensor; `null` si no existe.",
      "",
      "### Alertas automáticas",
      "",
      "- `recordReading(sensorId, value) -> [AlertView]` (update): registra una lectura del sensor, actualiza su `lastValue`, `lastReadingAt` y `status`, y **genera automáticamente** las alertas derivadas del rango configurado (`#belowMin` / `#aboveMax`) o de actividad de movimiento (`#movementDetected`). Devuelve las alertas creadas por esta lectura (lista vacía si la lectura está dentro de rango).",
      "- `listAlerts() -> [AlertView]` (query): todas las alertas, **de más reciente a más antigua**.",
      "- `getAlert(id) -> ?AlertView` (query): el detalle de una alerta —incluido el motivo (`reason`), el `value` que la disparó y el `message`— o `null`.",
      "- `markAlertRead(id) -> ?AlertView` (update): marca una alerta como leída; `null` si no existe.",
      "",
      "### Dispositivos vinculados",
      "",
      "- `linkDevice(name) -> LinkedDeviceView` (update): vincula un celular para recibir notificaciones dentro de la app.",
      "- `listDevices() -> [LinkedDeviceView]` (query): todos los dispositivos vinculados.",
      "- `unlinkDevice(id) -> Bool` (update): desvincula un dispositivo; `true` si existía y se eliminó, `false` en caso contrario.",
      "",
      "## Ciclo de vida y sondeo",
      "",
      "- Las lecturas son `query` (rápidas, no replicadas) y las escrituras son `update`. Tras una escritura, vuelve a consultar la lista correspondiente para reflejar el nuevo estado.",
      "- El estado del sensor (`#normal` / `#outOfRange`) y las alertas se actualizan únicamente al llamar a `recordReading`; no hay proceso en segundo plano.",
      "- Para ver alertas nuevas, sondea `listAlerts()` o `getAlert(id)`; las alertas no leídas tienen `read = false`.",
      "",
      "## Reintentos e idempotencia",
      "",
      "- `registerFarol` es seguro de reintentar con el mismo `qrCode`: no duplica el farol, pero **sí añade otra entrada de posición** por cada llamada, así que un reintento tras un error de red puede duplicar el historial.",
      "- `recordReading` **no es idempotente**: cada llamada añade una lectura y puede crear alertas nuevas. No lo reintentes a ciegas.",
      "- `addSensor` y `linkDevice` **no son idempotentes**: cada llamada crea un registro nuevo con un id nuevo, incluso con el mismo `name` o `qrCode`.",
      "- `markAlertRead` y `unlinkDevice` sí son idempotentes en efecto: repetir la llamada deja el mismo estado final (`unlinkDevice` devuelve `false` la segunda vez porque el registro ya no existe).",
      "- `updateSensorRange` es idempotente: repetir con los mismos valores deja el mismo rango.",
      "",
      "## Errores y límites",
      "",
      "- Los endpoints que devuelven `?T` usan `null` para \"no existe\"; no lanzan error por una ausencia normal.",
      "- Un llamador anónimo o no registrado es rechazado en los endpoints protegidos.",
      "- `recordReading` con un `sensorId` inexistente es un error del llamador.",
      "- No hay paginación: las listas devuelven todos los registros.",
      "- No hay endpoints de borrado para faroles, sensores ni alertas.",
      "",
    ];
    lines.values().join("\n");
  };
};
