/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const SensorType = IDL.Variant({
  'movement' : IDL.Null,
  'temperature' : IDL.Null,
  'humidity' : IDL.Null,
  'battery' : IDL.Null,
});
export const FarolId = IDL.Nat;
export const SensorId = IDL.Nat;
export const SensorStatus = IDL.Variant({
  'normal' : IDL.Null,
  'outOfRange' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const SensorView = IDL.Record({
  'id' : SensorId,
  'status' : SensorStatus,
  'sensorType' : SensorType,
  'minValue' : IDL.Float64,
  'farolId' : IDL.Opt(FarolId),
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'lastValue' : IDL.Opt(IDL.Float64),
  'maxValue' : IDL.Float64,
  'lastReadingAt' : IDL.Opt(Timestamp),
  'qrCode' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AlertId = IDL.Nat;
export const AlertReason = IDL.Variant({
  'movementDetected' : IDL.Null,
  'aboveMax' : IDL.Null,
  'belowMin' : IDL.Null,
});
export const AlertView = IDL.Record({
  'id' : AlertId,
  'value' : IDL.Float64,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'sensorId' : SensorId,
  'message' : IDL.Text,
  'reason' : AlertReason,
});
export const FarolView = IDL.Record({
  'id' : FarolId,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'registeredAt' : Timestamp,
  'qrCode' : IDL.Text,
});
export const DeviceId = IDL.Nat;
export const LinkedDeviceView = IDL.Record({
  'id' : DeviceId,
  'linkedAt' : Timestamp,
  'name' : IDL.Text,
});
export const PositionId = IDL.Nat;
export const PositionEntryView = IDL.Record({
  'id' : PositionId,
  'latitude' : IDL.Float64,
  'farolId' : FarolId,
  'recordedAt' : Timestamp,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addSensor' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        SensorType,
        IDL.Opt(FarolId),
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [SensorView],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAlert' : IDL.Func([AlertId], [IDL.Opt(AlertView)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFarol' : IDL.Func([FarolId], [IDL.Opt(FarolView)], ['query']),
  'getSensor' : IDL.Func([SensorId], [IDL.Opt(SensorView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkDevice' : IDL.Func([IDL.Text], [LinkedDeviceView], []),
  'listAlerts' : IDL.Func([], [IDL.Vec(AlertView)], ['query']),
  'listDevices' : IDL.Func([], [IDL.Vec(LinkedDeviceView)], ['query']),
  'listFaroles' : IDL.Func([], [IDL.Vec(FarolView)], ['query']),
  'listPositions' : IDL.Func(
      [FarolId],
      [IDL.Vec(PositionEntryView)],
      ['query'],
    ),
  'listSensors' : IDL.Func(
      [IDL.Opt(SensorType), IDL.Opt(SensorStatus), IDL.Opt(IDL.Text)],
      [IDL.Vec(SensorView)],
      ['query'],
    ),
  'markAlertRead' : IDL.Func([AlertId], [IDL.Opt(AlertView)], []),
  'recordReading' : IDL.Func([SensorId, IDL.Float64], [IDL.Vec(AlertView)], []),
  'registerFarol' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [FarolView],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'unlinkDevice' : IDL.Func([DeviceId], [IDL.Bool], []),
  'updateSensorRange' : IDL.Func(
      [SensorId, IDL.Float64, IDL.Float64],
      [IDL.Opt(SensorView)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const SensorType = IDL.Variant({
    'movement' : IDL.Null,
    'temperature' : IDL.Null,
    'humidity' : IDL.Null,
    'battery' : IDL.Null,
  });
  const FarolId = IDL.Nat;
  const SensorId = IDL.Nat;
  const SensorStatus = IDL.Variant({
    'normal' : IDL.Null,
    'outOfRange' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const SensorView = IDL.Record({
    'id' : SensorId,
    'status' : SensorStatus,
    'sensorType' : SensorType,
    'minValue' : IDL.Float64,
    'farolId' : IDL.Opt(FarolId),
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'lastValue' : IDL.Opt(IDL.Float64),
    'maxValue' : IDL.Float64,
    'lastReadingAt' : IDL.Opt(Timestamp),
    'qrCode' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AlertId = IDL.Nat;
  const AlertReason = IDL.Variant({
    'movementDetected' : IDL.Null,
    'aboveMax' : IDL.Null,
    'belowMin' : IDL.Null,
  });
  const AlertView = IDL.Record({
    'id' : AlertId,
    'value' : IDL.Float64,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'sensorId' : SensorId,
    'message' : IDL.Text,
    'reason' : AlertReason,
  });
  const FarolView = IDL.Record({
    'id' : FarolId,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'registeredAt' : Timestamp,
    'qrCode' : IDL.Text,
  });
  const DeviceId = IDL.Nat;
  const LinkedDeviceView = IDL.Record({
    'id' : DeviceId,
    'linkedAt' : Timestamp,
    'name' : IDL.Text,
  });
  const PositionId = IDL.Nat;
  const PositionEntryView = IDL.Record({
    'id' : PositionId,
    'latitude' : IDL.Float64,
    'farolId' : FarolId,
    'recordedAt' : Timestamp,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addSensor' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          SensorType,
          IDL.Opt(FarolId),
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [SensorView],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAlert' : IDL.Func([AlertId], [IDL.Opt(AlertView)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFarol' : IDL.Func([FarolId], [IDL.Opt(FarolView)], ['query']),
    'getSensor' : IDL.Func([SensorId], [IDL.Opt(SensorView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkDevice' : IDL.Func([IDL.Text], [LinkedDeviceView], []),
    'listAlerts' : IDL.Func([], [IDL.Vec(AlertView)], ['query']),
    'listDevices' : IDL.Func([], [IDL.Vec(LinkedDeviceView)], ['query']),
    'listFaroles' : IDL.Func([], [IDL.Vec(FarolView)], ['query']),
    'listPositions' : IDL.Func(
        [FarolId],
        [IDL.Vec(PositionEntryView)],
        ['query'],
      ),
    'listSensors' : IDL.Func(
        [IDL.Opt(SensorType), IDL.Opt(SensorStatus), IDL.Opt(IDL.Text)],
        [IDL.Vec(SensorView)],
        ['query'],
      ),
    'markAlertRead' : IDL.Func([AlertId], [IDL.Opt(AlertView)], []),
    'recordReading' : IDL.Func(
        [SensorId, IDL.Float64],
        [IDL.Vec(AlertView)],
        [],
      ),
    'registerFarol' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [FarolView],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'unlinkDevice' : IDL.Func([DeviceId], [IDL.Bool], []),
    'updateSensorRange' : IDL.Func(
        [SensorId, IDL.Float64, IDL.Float64],
        [IDL.Opt(SensorView)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };