/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertId = bigint;
export type AlertReason = { 'movementDetected' : null } |
  { 'aboveMax' : null } |
  { 'belowMin' : null };
export interface AlertView {
  'id' : AlertId,
  'value' : number,
  'createdAt' : Timestamp,
  'read' : boolean,
  'sensorId' : SensorId,
  'message' : string,
  'reason' : AlertReason,
}
export interface Cell { 'value' : Value, 'name' : string }
export type DeviceId = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FarolId = bigint;
export interface FarolView {
  'id' : FarolId,
  'latitude' : number,
  'name' : string,
  'longitude' : number,
  'registeredAt' : Timestamp,
  'qrCode' : string,
}
export interface LinkedDeviceView {
  'id' : DeviceId,
  'linkedAt' : Timestamp,
  'name' : string,
}
export interface PositionEntryView {
  'id' : PositionId,
  'latitude' : number,
  'farolId' : FarolId,
  'recordedAt' : Timestamp,
  'longitude' : number,
}
export type PositionId = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type SensorId = bigint;
export type SensorStatus = { 'normal' : null } |
  { 'outOfRange' : null };
export type SensorType = { 'movement' : null } |
  { 'temperature' : null } |
  { 'humidity' : null } |
  { 'battery' : null };
export interface SensorView {
  'id' : SensorId,
  'status' : SensorStatus,
  'sensorType' : SensorType,
  'minValue' : number,
  'farolId' : [] | [FarolId],
  'name' : string,
  'unit' : string,
  'lastValue' : [] | [number],
  'maxValue' : number,
  'lastReadingAt' : [] | [Timestamp],
  'qrCode' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add a sensor manually or from its own QR code.
   */
  'addSensor' : ActorMethod<
    [string, string, SensorType, [] | [FarolId], string, number, number],
    SensorView
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Fetch a single alert by id.
   */
  'getAlert' : ActorMethod<[AlertId], [] | [AlertView]>,
  /**
   * / Static Markdown documentation of the public backend API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch a single farol by id.
   */
  'getFarol' : ActorMethod<[FarolId], [] | [FarolView]>,
  /**
   * / Fetch a single sensor by id.
   */
  'getSensor' : ActorMethod<[SensorId], [] | [SensorView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Link a mobile phone as a registered device.
   */
  'linkDevice' : ActorMethod<[string], LinkedDeviceView>,
  /**
   * / List alerts, newest first.
   */
  'listAlerts' : ActorMethod<[], Array<AlertView>>,
  /**
   * / List every linked device.
   */
  'listDevices' : ActorMethod<[], Array<LinkedDeviceView>>,
  /**
   * / List every registered farol.
   */
  'listFaroles' : ActorMethod<[], Array<FarolView>>,
  /**
   * / Position history for a farol, newest first.
   */
  'listPositions' : ActorMethod<[FarolId], Array<PositionEntryView>>,
  /**
   * / List sensors with optional type, status and search filters.
   */
  'listSensors' : ActorMethod<
    [[] | [SensorType], [] | [SensorStatus], [] | [string]],
    Array<SensorView>
  >,
  /**
   * / Mark an alert as read.
   */
  'markAlertRead' : ActorMethod<[AlertId], [] | [AlertView]>,
  /**
   * / Record a sensor reading; alerts are derived automatically from the
   * / configured min/max range (or movement activity).
   */
  'recordReading' : ActorMethod<[SensorId, number], Array<AlertView>>,
  /**
   * / Register a farol from a QR scan, capturing the device GPS position.
   */
  'registerFarol' : ActorMethod<[string, string, number, number], FarolView>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Unlink a device by id.
   */
  'unlinkDevice' : ActorMethod<[DeviceId], boolean>,
  /**
   * / Update the configured min/max range of a sensor.
   */
  'updateSensorRange' : ActorMethod<
    [SensorId, number, number],
    [] | [SensorView]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];