/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type AlertId = bigint;
export interface AlertView {
    id: AlertId;
    value: number;
    createdAt: Timestamp;
    read: boolean;
    sensorId: SensorId;
    message: string;
    reason: AlertReason;
}
export interface Cell {
    value: Value;
    name: string;
}
export type DeviceId = bigint;
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type FarolId = bigint;
export interface FarolView {
    id: FarolId;
    latitude: number;
    name: string;
    longitude: number;
    registeredAt: Timestamp;
    qrCode: string;
}
export interface LinkedDeviceView {
    id: DeviceId;
    linkedAt: Timestamp;
    name: string;
}
export interface PositionEntryView {
    id: PositionId;
    latitude: number;
    farolId: FarolId;
    recordedAt: Timestamp;
    longitude: number;
}
export type PositionId = bigint;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type SensorId = bigint;
export interface SensorView {
    id: SensorId;
    status: SensorStatus;
    sensorType: SensorType;
    minValue: number;
    farolId?: FarolId;
    name: string;
    unit: string;
    lastValue?: number;
    maxValue: number;
    lastReadingAt?: Timestamp;
    qrCode: string;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum AlertReason {
    movementDetected = "movementDetected",
    aboveMax = "aboveMax",
    belowMin = "belowMin"
}
export enum SensorStatus {
    normal = "normal",
    outOfRange = "outOfRange"
}
export enum SensorType {
    movement = "movement",
    temperature = "temperature",
    humidity = "humidity",
    battery = "battery"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Add a sensor manually or from its own QR code.
     */
    addSensor(name: string, qrCode: string, sensorType: SensorType, farolId: FarolId | null, unit: string, minValue: number, maxValue: number): Promise<SensorView>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Fetch a single alert by id.
     */
    getAlert(id: AlertId): Promise<AlertView | null>;
    /**
     * / Static Markdown documentation of the public backend API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch a single farol by id.
     */
    getFarol(id: FarolId): Promise<FarolView | null>;
    /**
     * / Fetch a single sensor by id.
     */
    getSensor(id: SensorId): Promise<SensorView | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Link a mobile phone as a registered device.
     */
    linkDevice(name: string): Promise<LinkedDeviceView>;
    /**
     * / List alerts, newest first.
     */
    listAlerts(): Promise<Array<AlertView>>;
    /**
     * / List every linked device.
     */
    listDevices(): Promise<Array<LinkedDeviceView>>;
    /**
     * / List every registered farol.
     */
    listFaroles(): Promise<Array<FarolView>>;
    /**
     * / Position history for a farol, newest first.
     */
    listPositions(farolId: FarolId): Promise<Array<PositionEntryView>>;
    /**
     * / List sensors with optional type, status and search filters.
     */
    listSensors(sensorType: SensorType | null, status: SensorStatus | null, search: string | null): Promise<Array<SensorView>>;
    /**
     * / Mark an alert as read.
     */
    markAlertRead(id: AlertId): Promise<AlertView | null>;
    /**
     * / Record a sensor reading; alerts are derived automatically from the
     * / configured min/max range (or movement activity).
     */
    recordReading(sensorId: SensorId, value: number): Promise<Array<AlertView>>;
    /**
     * / Register a farol from a QR scan, capturing the device GPS position.
     */
    registerFarol(qrCode: string, name: string, latitude: number, longitude: number): Promise<FarolView>;
    schema(): Promise<string>;
    /**
     * / Unlink a device by id.
     */
    unlinkDevice(id: DeviceId): Promise<boolean>;
    /**
     * / Update the configured min/max range of a sensor.
     */
    updateSensorRange(id: SensorId, minValue: number, maxValue: number): Promise<SensorView | null>;
}
import type { AlertId as _AlertId, AlertReason as _AlertReason, AlertView as _AlertView, Cell as _Cell, Error as _Error, FarolId as _FarolId, FarolView as _FarolView, Result as _Result, Result__1 as _Result__1, SensorId as _SensorId, SensorStatus as _SensorStatus, SensorType as _SensorType, SensorView as _SensorView, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addSensor(arg0: string, arg1: string, arg2: SensorType, arg3: FarolId | null, arg4: string, arg5: number, arg6: number): Promise<SensorView> {
        if (this.processError) {
            try {
                const result = await this.actor.addSensor(arg0, arg1, to_candid_SensorType_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return from_candid_SensorView_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSensor(arg0, arg1, to_candid_SensorType_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return from_candid_SensorView_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlert(arg0: AlertId): Promise<AlertView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlert(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlert(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarol(arg0: FarolId): Promise<FarolView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarol(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarol(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSensor(arg0: SensorId): Promise<SensorView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSensor(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSensor(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkDevice(arg0: string): Promise<LinkedDeviceView> {
        if (this.processError) {
            try {
                const result = await this.actor.linkDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkDevice(arg0);
            return result;
        }
    }
    async listAlerts(): Promise<Array<AlertView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlerts();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlerts();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDevices(): Promise<Array<LinkedDeviceView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDevices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDevices();
            return result;
        }
    }
    async listFaroles(): Promise<Array<FarolView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFaroles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFaroles();
            return result;
        }
    }
    async listPositions(arg0: FarolId): Promise<Array<PositionEntryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPositions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPositions(arg0);
            return result;
        }
    }
    async listSensors(arg0: SensorType | null, arg1: SensorStatus | null, arg2: string | null): Promise<Array<SensorView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSensors(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSensors(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAlertRead(arg0: AlertId): Promise<AlertView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markAlertRead(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAlertRead(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordReading(arg0: SensorId, arg1: number): Promise<Array<AlertView>> {
        if (this.processError) {
            try {
                const result = await this.actor.recordReading(arg0, arg1);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordReading(arg0, arg1);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerFarol(arg0: string, arg1: string, arg2: number, arg3: number): Promise<FarolView> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFarol(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFarol(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async unlinkDevice(arg0: DeviceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlinkDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlinkDevice(arg0);
            return result;
        }
    }
    async updateSensorRange(arg0: SensorId, arg1: number, arg2: number): Promise<SensorView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSensorRange(arg0, arg1, arg2);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSensorRange(arg0, arg1, arg2);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AlertReason_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertReason): AlertReason {
    return "movementDetected" in value ? AlertReason.movementDetected : "aboveMax" in value ? AlertReason.aboveMax : "belowMin" in value ? AlertReason.belowMin : value;
}
function from_candid_AlertView_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertView): AlertView {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SensorStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SensorStatus): SensorStatus {
    return "normal" in value ? SensorStatus.normal : "outOfRange" in value ? SensorStatus.outOfRange : value;
}
function from_candid_SensorType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SensorType): SensorType {
    return "movement" in value ? SensorType.movement : "temperature" in value ? SensorType.temperature : "humidity" in value ? SensorType.humidity : "battery" in value ? SensorType.battery : value;
}
function from_candid_SensorView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SensorView): SensorView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FarolId]): FarolId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AlertView]): AlertView | null {
    return value.length === 0 ? null : from_candid_AlertView_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FarolView]): FarolView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SensorView]): SensorView | null {
    return value.length === 0 ? null : from_candid_SensorView_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n17(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n21(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AlertId;
    value: number;
    createdAt: _Timestamp;
    read: boolean;
    sensorId: _SensorId;
    message: string;
    reason: _AlertReason;
}): {
    id: AlertId;
    value: number;
    createdAt: Timestamp;
    read: boolean;
    sensorId: SensorId;
    message: string;
    reason: AlertReason;
} {
    return {
        id: value.id,
        value: value.value,
        createdAt: value.createdAt,
        read: value.read,
        sensorId: value.sensorId,
        message: value.message,
        reason: from_candid_AlertReason_n26(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SensorId;
    status: _SensorStatus;
    sensorType: _SensorType;
    minValue: number;
    farolId: [] | [_FarolId];
    name: string;
    unit: string;
    lastValue: [] | [number];
    maxValue: number;
    lastReadingAt: [] | [_Timestamp];
    qrCode: string;
}): {
    id: SensorId;
    status: SensorStatus;
    sensorType: SensorType;
    minValue: number;
    farolId?: FarolId;
    name: string;
    unit: string;
    lastValue?: number;
    maxValue: number;
    lastReadingAt?: Timestamp;
    qrCode: string;
} {
    return {
        id: value.id,
        status: from_candid_SensorStatus_n9(_uploadFile, _downloadFile, value.status),
        sensorType: from_candid_SensorType_n10(_uploadFile, _downloadFile, value.sensorType),
        minValue: value.minValue,
        farolId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.farolId)),
        name: value.name,
        unit: value.unit,
        lastValue: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.lastValue)),
        maxValue: value.maxValue,
        lastReadingAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastReadingAt)),
        qrCode: value.qrCode
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlertView>): Array<AlertView> {
    return value.map((x)=>from_candid_AlertView_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SensorView>): Array<SensorView> {
    return value.map((x)=>from_candid_SensorView_n7(_uploadFile, _downloadFile, x));
}
function to_candid_SensorStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SensorStatus): _SensorStatus {
    return value == SensorStatus.normal ? {
        normal: null
    } : value == SensorStatus.outOfRange ? {
        outOfRange: null
    } : value;
}
function to_candid_SensorType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SensorType): _SensorType {
    return value == SensorType.movement ? {
        movement: null
    } : value == SensorType.temperature ? {
        temperature: null
    } : value == SensorType.humidity ? {
        humidity: null
    } : value == SensorType.battery ? {
        battery: null
    } : value;
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SensorType | null): [] | [_SensorType] {
    return value === null ? candid_none() : candid_some(to_candid_SensorType_n5(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SensorStatus | null): [] | [_SensorStatus] {
    return value === null ? candid_none() : candid_some(to_candid_SensorStatus_n33(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarolId | null): [] | [_FarolId] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
